//Source code generated by AppGPT (www.appgpt.tech)
import { mergeTranslations } from 'ra-core';
import polyglotI18nProvider from 'ra-i18n-polyglot';
import enOriginal from 'ra-language-english';
import frOriginal from 'ra-language-french';

const enResources = {
  resources: {
    users: {
      name: 'Users',
      fields: {
        username: 'Username',
        email: 'Email',
        password: 'Password',
        profilePictureURL: 'Profile Picture Url',
        status: 'Status',
        id: 'id',
      },
    },
    messages: {
      name: 'Messages',
      fields: {
        senderID: 'Sender Id',
        chatID: 'Chat Id',
        content: 'Content',
        timestamp: 'Timestamp',
        id: 'id',
      },
    },
    chats: {
      name: 'Chats',
      fields: {
        chatID: 'Chat Id',
        participants: 'Participants',
        chatName: 'Chat Name',
        lastMessage: 'Last Message',
        id: 'id',
      },
    },
    contacts: {
      name: 'Contacts',
      fields: {
        contactName: 'Contact Name',
        profilePictureURL: 'Profile Picture Url',
        id: 'id',
      },
    },
  },
};
const frResources = {
  resources: {
    users: {
      name: 'Users (fr)',
      fields: {
        username: 'Username (fr)',
        email: 'Email (fr)',
        password: 'Password (fr)',
        profilePictureURL: 'Profile Picture Url (fr)',
        status: 'Status (fr)',
        id: 'id',
      },
    },
    messages: {
      name: 'Messages (fr)',
      fields: {
        senderID: 'Sender Id (fr)',
        chatID: 'Chat Id (fr)',
        content: 'Content (fr)',
        timestamp: 'Timestamp (fr)',
        id: 'id',
      },
    },
    chats: {
      name: 'Chats (fr)',
      fields: {
        chatID: 'Chat Id (fr)',
        participants: 'Participants (fr)',
        chatName: 'Chat Name (fr)',
        lastMessage: 'Last Message (fr)',
        id: 'id',
      },
    },
    contacts: {
      name: 'Contacts (fr)',
      fields: {
        contactName: 'Contact Name (fr)',
        profilePictureURL: 'Profile Picture Url (fr)',
        id: 'id',
      },
    },
  },
};

const en = mergeTranslations(enOriginal, enResources);
const fr = mergeTranslations(frOriginal, frResources);

const translations = { en, fr };
export const i18nProvider = polyglotI18nProvider(
  (locale) => translations[locale],
  'en', //default locale
  [
    { locale: 'en', name: 'English' },
    { locale: 'fr', name: 'Français' },
  ],
);
